refactor(bin/s0cks): 🔨 cleanup s0cks utility code

diff --git a/bin/s0cks b/bin/s0cks
--- a/bin/s0cks
+++ b/bin/s0cks
@@ -1,171 +1,170 @@
 #!/usr/bin/env zsh
 autoload -Uz colors && colors
 
+local VERSION="0.0.1"
+local USAGE=(
+  "Usage: s0cks [-h|--help] [<cmd>]"
+  "General Options:"
+  "  -h|--help        # Print help and usage info"
+  "  -v|--verbose     # Print more, mostly debug, info to the console while working"
+  ""
+  "cmds:"
+  "   version         # Prints the version to the console"
+  "   update [target] # Perform an update with an optional target"
+)
+local verbose=false
+local update_target
+local DOTFILES_DIR=${DOTFILES_DIR:-/usr/local/share/dotfiles}
+local NEOVIM_DIR=${NEOVIM_HOME:-${XDG_CONFIG_HOME}/nvim}
+local WEZTERM_DIR=${WEZTERM_HOME:-${XDG_CONFIG_HOME}/wezterm}
+local HAMMERSPOON_DIR=${HAMMERSPOON_DIR:-${XDG_CONFIG_HOME}/hammerspoon}
 
+local __show_help() {
+  printf "%s\n" $USAGE
+}
 
-s0cks() {
-  local VERSION="0.0.1"
-  local USAGE=(
-    "Usage: s0cks [-h|--help] [<cmd>]"
-    "General Options:"
-    "  -h|--help        # Print help and usage info"
-    "  -v|--verbose     # Print more, mostly debug, info to the console while working"
-    ""
-    "cmds:"
-    "   version         # Prints the version to the console"
-    "   update [target] # Perform an update with an optional target"
-  )
-  local show_version() {
-    printf "s0cks %s\n" "$VERSION"
-  }
-  
-  local cmd=()
-  local verbose=false
-  local update_target
-  local DOTFILES_DIR=${DOTFILES_DIR:-/usr/local/share/dotfiles}
-  local NEOVIM_DIR=${NEOVIM_HOME:-${XDG_CONFIG_HOME}/nvim}
-  local WEZTERM_DIR=${WEZTERM_HOME:-${XDG_CONFIG_HOME}/wezterm}
-  local HAMMERSPOON_DIR=${HAMMERSPOON_DIR:-${XDG_CONFIG_HOME}/hammerspoon}
+local __show_version() {
+  printf "s0cks %s\n" "$VERSION"
+}
 
-  local function __done() {
-    echo "$fg[green]${reset_color} done."
-  }
+local __done() {
+  echo "$fg[green]${reset_color} done."
+}
 
-  local function __updated() {
-    local name="$update_target"
-    local revision="$(git log -1 --pretty='%h %B')"
-    echo "$fg[green] $fg[bold]$fg[magenta]$name$reset_color updated to: $revision"
-  }
+local __updated() {
+  local name="$update_target"
+  local revision="$(git log -1 --pretty='%h %B')"
+  echo "$fg[green] $fg[bold]$fg[magenta]$name$reset_color updated to: $revision"
+}
 
-  local function __pull_changes() {
-    local name="$update_target"
-    local version="$(git rev-parse --abbrev-ref HEAD)"
-    local remote="$(git remote get-url origin)"
-    git pull --recurse-submodules &>/dev/null
-    if (( "$?" != 0 )); then
-      echo "$fg[red]$reset_color failed. Can't update $name $version from remote: $remote"
-      return 1
-    fi
-    return 0
-  }
+local __pull_changes() {
+  local name="$update_target"
+  local version="$(git rev-parse --abbrev-ref HEAD)"
+  local remote="$(git remote get-url origin)"
+  git pull --recurse-submodules &>/dev/null
+  if (( "$?" != 0 )); then
+    echo "$fg[red]$reset_color failed. Can't update $name $version from remote: $remote"
+    return 1
+  fi
+  return 0
+}
 
-  local function __no_updates() {
-    echo "$bold$fg[yellow]$reset_color skipped, no updates."
-  }
+local __no_updates() {
+  echo "$bold$fg[yellow]$reset_color skipped, no updates."
+}
 
-  local function __updating() {
-    local name="$update_target"
-    if [[ "$verbose" == "true" ]]; then
-      echo "updating $bold$fg[magenta]$name$reset_color in $fg[cyan]$(pwd)$reset_color...."
-    else
-      echo "updating $bold$fg[magenta]$name$reset_color...."
-    fi
-  }
+local __updating() {
+  local name="$update_target"
+  if [[ "$verbose" == "true" ]]; then
+    echo "updating $bold$fg[magenta]$name$reset_color in $fg[cyan]$(pwd)$reset_color...."
+  else
+    echo "updating $bold$fg[magenta]$name$reset_color...."
+  fi
+}
 
-  local update_dotfiles() {
-    update_target="dotfiles"
-    pushd "$DOTFILES_DIR/"
-    local prev="$(git log -1 --pretty='%h')"
-    __updating
-    __pull_changes
+local __update_dotfiles() {
+  update_target="dotfiles"
+  pushd "$DOTFILES_DIR/"
+  local prev="$(git log -1 --pretty='%h')"
+  __updating
+  __pull_changes
 
-    task install &>/dev/null
-    if (( "$?" != 0)); then
-      echo "$fg[red]${reset_color} failed to install dotfiles"
-      return 1
-    fi
-
-    local crev="$(git log -1 --pretty='%h')"
-    if [[ "$prev" != "$crev" ]]; then
-      __updated
-    else
-      __no_updates
-    fi
-    popd &>/dev/null
-    return 0
-  }
-  
-  local __update_app_config() {
-    update_target="$1"
-    pushd "$2"
-    local prev="$(git log -1 --pretty='%h')"
-    __updating
-    __pull_changes
-
-    local crev="$(git log -1 --pretty='%h')"
-    if [[ "$prev" != "$crev" ]]; then
-      __updated
-    else
-      __no_updates
-    fi
-    popd &>/dev/null
-    return 0
-  }
-
-  opterr() {
-    echo >&2 "optparsing_demo: Unknown option '$1'"
-  }
-
-  show_help() {
-    printf "%s\n" $USAGE
-  }
-
-  while (( $# )); do
-    case $1 in
-      --)
-        shift;
-        cmd+=("${@[@]}");
-        break
-        ;;
-      -h|--help)          
-        show_help
-        return
-        ;;
-      -v|--verbose)
-        verbose=true
-        ;;
-      -*)                 opterr $1 && return 2                   ;;
-      *)                  cmd+=("${@[@]}"); break             ;;
-    esac
-    shift
-  done
-
-  if (( "${#cmd[@]}" == 0)); then
-    show_help
-    return
+  task install &>/dev/null
+  if (( "$?" != 0)); then
+    echo "$fg[red]${reset_color} failed to install dotfiles"
+    return 1
   fi
 
+  local crev="$(git log -1 --pretty='%h')"
+  if [[ "$prev" != "$crev" ]]; then
+    __updated
+  else
+    __no_updates
+  fi
+  popd &>/dev/null
+  return 0
+}
 
-  case "${cmd[1]}" in
-    version)
-      show_version
+local __update_app_config() {
+  update_target="$1"
+  pushd "$2"
+  local prev="$(git log -1 --pretty='%h')"
+  __updating
+  __pull_changes
+
+  local crev="$(git log -1 --pretty='%h')"
+  if [[ "$prev" != "$crev" ]]; then
+    __updated
+  else
+    __no_updates
+  fi
+  popd &>/dev/null
+  return 0
+}
+
+local __opterror() {
+  echo >&2 "s0cks: invalid option '$1'"
+}
+
+local cmd=()
+while (( $# )); do
+  case $1 in
+    --)
+      shift;
+      cmd+=("${@[@]}");
+      break
       ;;
-    update)
-      shift cmd
-      if (( "${#cmd[@]}" == 0 )); then
-        update_dotfiles
-      else
-        case "${cmd[1]}" in
-        dotfiles)
-          update_dotfiles
-          ;;
-        nvim|neovim)
-          __update_app_config "Neovim" "$NEOVIM_DIR"
-          ;;
-        wez|wezterm)
-          __update_app_config "WezTerm" "$WEZTERM_DIR"
-          ;;
-        hs|hammerspoon)
-          __update_app_config "Hammerspoon" "$HAMMERSPOON_DIR"
-          ;;
-        *)
-          opterr "$cmd" && return 2
-          ;;
-        esac
-      fi
+    -h|--help)
+      __show_help && return
+      ;;
+    -v|--verbose)
+      verbose=true
+      ;;
+    -*)
+      __opterr $1 && return 2
       ;; 
     *)
-      opterr "$@" && return 2
+      cmd+=("${@[@]}");
+      break
       ;;
   esac
-}
+  shift
+done
+
+if (( "${#cmd[@]}" == 0)); then
+  __show_help && return
+fi
+
+
+case "${cmd[1]}" in
+  version)
+    __show_version
+    ;;
+  update)
+    shift cmd
+    if (( "${#cmd[@]}" == 0 )); then
+      update_dotfiles
+    else
+      case "${cmd[1]}" in
+      dotfiles)
+        __update_dotfiles
+        ;;
+      nvim|neovim)
+        __update_app_config "Neovim" "$NEOVIM_DIR"
+        ;;
+      wez|wezterm)
+        __update_app_config "WezTerm" "$WEZTERM_DIR"
+        ;;
+      hs|hammerspoon)
+        __update_app_config "Hammerspoon" "$HAMMERSPOON_DIR"
+        ;;
+      *)
+        __opterror "$cmd" && return 2
+        ;;
+      esac
+    fi
+    ;; 
+  *)
+    __opterr "$@" && return 2
+    ;;
+esac
